### ISSUE TITLE
No sudo with common commands?

### ISSUE THREAD

**Issue by VikParuchuri** [openedx-unsupported/configuration#60]
I am periodically merging master into my branch that configures the ml api, and the biggest issue is the removal of sudo in the common playbook.  How is the lack of sudo working?

For example, this will fail:

```
- name: Create data dir
  file: path={{ app_base_dir }}/data state=directory owner=root group=root
  tags:
  - pre_install
```

This will succeed:

```
- name: Create data dir
  file: path={{ app_base_dir }}/data state=directory owner=root group=root
  sudo: True
  tags:
  - pre_install
```

Am I doing something wrong with users or the ansible command?

I am running:

```
ansible-playbook mlapi_sandbox.yml -i ./ec2.py -c ssh --user=ubuntu -v
```

This is happening in the aws-sandbox account, and the ansible command is bring run on a vpc.
