### ISSUE TITLE
top-level playbook organization

### ISSUE THREAD

**Issue by jarv** [openedx-unsupported/configuration#67]
I think it probably still makes sense to check-in the top-level playbooks to playbooks/ where we will each have our own for production/staging configurations that include different roles.

It would be nice to be able to organize them into sub-directories or even a different repo but I am pretty sure roles are relative to the playbook that are run and it would probably start to get ugly with relative pathing.

Does something like `{edx-east,edx-west}-<whatever>.yml` sound like a decent convention for now?

**Comment by jarv** [comment]
We could do something like this which isn't pretty but works, I talked to mdehaan on IRC and he said he would accept a patch that adds a configuration variable that will append to the role search path.

```
- hosts: tag_aws_cloudformation_stack-name_continuous-integration:&tag_group_edxapp
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_ref_vars.yml"
    - "{{ secure_dir }}/vars/edxapp_ref_users.yml"
  roles:
    - ../../../configuration/playbooks/roles/common
```
